version: "3"
services:
  movie:
    container_name: movie
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
    environment:
      - MONGO_CONNECTION=mongodb://mongodb:27017
      - DATABASE_NAME=movie-service
      - PORT=3000
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
